main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.IndexView.as_view(), name="home"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('portfolio/', views.PortfolioView.as_view(), name="portfolio"),
    path('portfolio/<slug:slug>',
         views.PortfolioDetailView.as_view(), name="portfolio_detail"),
    path('testimonial/', views.TestimonialView.as_view(), name="testimonial"),
    path('service/', views.ServiceView.as_view(), name="service"),
    path('skills/', views.SkillView.as_view(), name="skill"),
    path('qualification/', views.QualificationView.as_view(), name="qualification"),
    path('contact/', views.ContactView.as_view(), name="contact"),



]

portfolio_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Skill(models.Model):
    class Meta:
        verbose_name_plural = "Skills"
        verbose_name = "Skill"
    sort_id = models.CharField(max_length=5, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)

    def __str__(self) -> str:
        return self.name


class UserProfile(models.Model):
    class Meta:
        verbose_name_plural = "User Profiles"
        verbose_name = "User Profile"

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    name = models.CharField(max_length=100, blank=True, null=True)
    sub_title = models.CharField(max_length=100, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    about_bio = models.TextField(blank=True, null=True)
    about_image = models.ImageField(blank=True, null=True, upload_to="about")
    experience = models.IntegerField(default=1, blank=True, null=True)
    projects = models.IntegerField(default=5, blank=True, null=True)
    companies = models.IntegerField(default=1, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    class Meta:
        verbose_name_plural = "Contact Profiles"
        verbose_name = "Contact Profile"
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name", max_length=100)
    email = models.EmailField(verbose_name="Email")
    project = models.CharField(verbose_name="Project", max_length=200)
    message = models.TextField(verbose_name="Message")

    def __str__(self) -> str:
        return self.name


class Testimonial(models.Model):
    class Meta:
        verbose_name_plural = "Testimonials"
        verbose_name = "Testimonial"
        ordering = ["name"]

    thumbnail = models.ImageField(
        blank=True, null=True, upload_to="testimonial")
    name = models.CharField(max_length=200, blank=True, null=True)
    rate = models.IntegerField(blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=200, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name


class Media(models.Model):
    class Meta:
        verbose_name_plural = "Media Files"
        verbose_name = "Media File"
        ordering = ["name"]

    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Portfolio(models.Model):
    class Meta:
        verbose_name_plural = "Portfolios"
        verbose_name = "Portfolio"
        ordering = ["name"]

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    demo = models.FileField(blank=True, null=True, upload_to="portfolio_demo")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


class Qualification(models.Model):
    class Meta:
        verbose_name_plural = "Qualifications"
        verbose_name = "Qualification"
        ordering = ["year_from"]

    sort_id = models.CharField(max_length=3, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    sub_title = models.CharField(max_length=200, blank=True, null=True)
    year_from = models.IntegerField(blank=True, null=True)
    year_to = models.IntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.title


class Service(models.Model):
    class Meta:
        verbose_name_plural = "Services"
        verbose_name = "Service"

    title = models.CharField(max_length=50, blank=True, null=True)
    title2 = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.title


class Service_Detail(models.Model):
    class Meta:
        verbose_name_plural = "Service Details"
        verbose_name = "Service Detail"

    title = models.CharField(max_length=50, blank=True, null=True)
    desciption = models.CharField(max_length=200, blank=True, null=True)
    services = models.ForeignKey(
        Service, related_name="service_details", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

# Create your models here.

main/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'contact__input',
    }))
    email = forms.EmailField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'contact__input',
    }))
    project = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'contact__input',
    }))
    message = forms.CharField(max_length=1000, required=True, widget=forms.Textarea(attrs={
        'class': 'contact__input',
        'rows': 7,
    }))

    class Meta:
        model = ContactProfile
        fields = ('name', 'email', 'project', 'message',)

main/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import (UserProfile, Testimonial, Service,
                     Qualification, Portfolio, Skill, Service_Detail)

from django.views import generic

from . forms import ContactForm


class IndexView(generic.TemplateView):
    template_name = "main/index.html"

    """def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        testimonials = Testimonial.objects.filter(is_active=True)
        services = Service.objects.filter(is_active=True)
        portfolio = Portfolio.objects.filter(is_active=True)
        qualifications = Qualification.objects.filter(is_active=True)

        context["testimonials"] = testimonials
        context["services"] = services
        context["qualications"] = qualifications
        context["portfolio"] = portfolio
        return context"""


class ContactView(generic.FormView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, 'Cảm ơn tôi sẽ liên lạc lại bạn sớm nhất có thể!!')
        return super().form_valid(form)


class PortfolioView(generic.ListView):
    model = Portfolio
    template_name = "main/portfolio.html"

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class QualificationView(generic.ListView):
    model = Qualification
    template_name = "main/qualification.html"

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class SkillView(generic.ListView):
    model = Skill
    template_name = "main/skills.html"


class TestimonialView(generic.ListView):
    model = Testimonial
    template_name = "main/testimonial.html"

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class ServiceView(generic.ListView):
    model = Service
    template_name = "main/service.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        services = Service.objects.filter(is_active=True)
        context["services"] = services
        return context


class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    template_name = "main/portfolio_detail.html"


class AboutView(generic.TemplateView):
    model = UserProfile
    template_name = "main/about.html"


# Create your views here.

main/templates/main/partials/footer.html
{% load static %}
<!--==================== FOOTER ====================-->
    <footer class="footer">
        <div class="footer__bg">
            <div class="footer__container container grid">
                <div class="footer__name">
                    <h1 class="footer__title">{{me.first_name|title}}</h1>
                    <span class="footer__subtitle">{{me.userprofile.sub_title}}</span>
                </div>

                <ul class="footer__links">
                    <li>
                        <a href="{% url 'main:service' %}" class="footer__link">Services</a>
                    </li>
                    <li>
                        <a href="{% url 'main:portfolio' %}" class="footer__link">Portfolio</a>
                    </li>
                    <li>
                        <a href="{% url 'main:contact' %}" class="footer__link">Contactme</a>
                    </li>

                </ul>


                <div class="footer__socials">
                    <a href="https://www.facebook.com/" target="_blank" class="footer__social">
                        <i class="uil uil-facebook-f"></i>
                    </a>
                    <a href="https://www.instagram.com/" target="_blank" class="footer__social">
                        <i class="uil uil-instagram-alt"></i>
                    </a>
                    <a href="https://github.com/" target="_blank" class="footer__social">
                        <i class="uil uil-github"></i>
                    </a>
                </div>
            </div>
            <div class="footer__copyright">
                © {{me.userprofile.name}} nè {%  now "Y" %} . All rights reserved .

            </div>

    </footer>

main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

main/templates/main/partials/nav.html
{% load static %}
<!--==================== HEADER ====================-->
    <header class="header" id="header">
        <nav class="nav container">
            <a href="{% url 'main:home' %}" class="nav__logo">
                QuangDong
            </a>
            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    
                    <li class="nav__item">
                        <a href="{% url 'main:about' %}" class="nav__link">
                            <i class="uil uil-user nav__icon"></i> About
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'main:skill' %}" class="nav__link">
                            <i class="uil uil-file-alt nav__icon"></i> Skills
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'main:service' %}" class="nav__link">
                            <i class="uil uil-briefcase-alt nav__icon"></i> Services
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'main:portfolio' %}" class="nav__link">
                            <i class="uil uil-scenery nav__icon"></i> Portfolio

                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'main:qualification' %}" class="nav__link">
                            <i class="uil uil-scenery nav__icon"></i> Qualification

                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'main:testimonial' %}" class="nav__link active-link">
                            <i class="uil uil-estate nav__icon"></i> Testimonial
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'main:contact' %}" class="nav__link">
                            <i class="uil uil-message nav__icon"></i> Contact
                        </a>
                    </li>
                </ul>
                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!--Theme change button-->

                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps"></i>
                </div>
            </div>
        </nav>

    </header>