main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.IndexView.as_view(), name="home"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('portfolio/', views.PortfolioView.as_view(), name="portfolio"),
    path('portfolio/<slug:slug>',
         views.PortfolioDetailView.as_view(), name="portfolio_detail"),
    path('testimonial/', views.TestimonialView.as_view(), name="testimonial"),
    path('service/', views.ServiceView.as_view(), name="service"),
    path('skills/', views.SkillView.as_view(), name="skill"),
    path('qualification/', views.QualificationView.as_view(), name="qualification"),
    path('contact/', views.ContactView.as_view(), name="contact"),



]

portfolio_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Skill(models.Model):
    class Meta:
        verbose_name_plural = "Skills"
        verbose_name = "Skill"
    sort_id = models.CharField(max_length=5, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)

    def __str__(self) -> str:
        return self.name


class UserProfile(models.Model):
    class Meta:
        verbose_name_plural = "User Profiles"
        verbose_name = "User Profile"

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    name = models.CharField(max_length=100, blank=True, null=True)
    sub_title = models.CharField(max_length=100, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    about_bio = models.TextField(blank=True, null=True)
    about_image = models.ImageField(blank=True, null=True, upload_to="about")
    experience = models.IntegerField(default=1, blank=True, null=True)
    projects = models.IntegerField(default=5, blank=True, null=True)
    companies = models.IntegerField(default=1, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    class Meta:
        verbose_name_plural = "Contact Profiles"
        verbose_name = "Contact Profile"
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name", max_length=100)
    email = models.EmailField(verbose_name="Email")
    project = models.CharField(verbose_name="Project", max_length=200)
    message = models.TextField(verbose_name="Message")

    def __str__(self) -> str:
        return self.name


class Testimonial(models.Model):
    class Meta:
        verbose_name_plural = "Testimonials"
        verbose_name = "Testimonial"
        ordering = ["name"]

    thumbnail = models.ImageField(
        blank=True, null=True, upload_to="testimonial")
    name = models.CharField(max_length=200, blank=True, null=True)
    rate = models.IntegerField(blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=200, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name


class Media(models.Model):
    class Meta:
        verbose_name_plural = "Media Files"
        verbose_name = "Media File"
        ordering = ["name"]

    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Portfolio(models.Model):
    class Meta:
        verbose_name_plural = "Portfolios"
        verbose_name = "Portfolio"
        ordering = ["name"]

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    demo = models.FileField(blank=True, null=True, upload_to="portfolio_demo")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


class Qualification(models.Model):
    class Meta:
        verbose_name_plural = "Qualifications"
        verbose_name = "Qualification"
        ordering = ["year_from"]

    sort_id = models.CharField(max_length=3, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    sub_title = models.CharField(max_length=200, blank=True, null=True)
    year_from = models.IntegerField(blank=True, null=True)
    year_to = models.IntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.title


class Service(models.Model):
    class Meta:
        verbose_name_plural = "Services"
        verbose_name = "Service"

    title = models.CharField(max_length=50, blank=True, null=True)
    title2 = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.title


class Service_Detail(models.Model):
    class Meta:
        verbose_name_plural = "Service Details"
        verbose_name = "Service Detail"

    title = models.CharField(max_length=50, blank=True, null=True)
    desciption = models.CharField(max_length=200, blank=True, null=True)
    services = models.ForeignKey(
        Service, related_name="service_details", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

# Create your models here.

main/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'contact__input',
    }))
    email = forms.EmailField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'contact__input',
    }))
    project = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
        'class': 'contact__input',
    }))
    message = forms.CharField(max_length=1000, required=True, widget=forms.Textarea(attrs={
        'class': 'contact__input',
        'rows': 7,
    }))

    class Meta:
        model = ContactProfile
        fields = ('name', 'email', 'project', 'message',)

main/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import (UserProfile, Testimonial, Service,
                     Qualification, Portfolio, Skill, Service_Detail)

from django.views import generic

from . forms import ContactForm


class IndexView(generic.TemplateView):
    template_name = "main/index.html"

    """def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        testimonials = Testimonial.objects.filter(is_active=True)
        services = Service.objects.filter(is_active=True)
        portfolio = Portfolio.objects.filter(is_active=True)
        qualifications = Qualification.objects.filter(is_active=True)

        context["testimonials"] = testimonials
        context["services"] = services
        context["qualications"] = qualifications
        context["portfolio"] = portfolio
        return context"""


class ContactView(generic.FormView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, 'Cảm ơn tôi sẽ liên lạc lại bạn sớm nhất có thể!!')
        return super().form_valid(form)


class PortfolioView(generic.ListView):
    model = Portfolio
    template_name = "main/portfolio.html"

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class QualificationView(generic.ListView):
    model = Qualification
    template_name = "main/qualification.html"

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class SkillView(generic.ListView):
    model = Skill
    template_name = "main/skills.html"


class TestimonialView(generic.ListView):
    model = Testimonial
    template_name = "main/testimonial.html"

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class ServiceView(generic.ListView):
    model = Service
    template_name = "main/service.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        services = Service.objects.filter(is_active=True)
        context["services"] = services
        return context


class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    template_name = "main/portfolio_detail.html"


class AboutView(generic.TemplateView):
    model = UserProfile
    template_name = "main/about.html"


# Create your views here.

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}

<!--SEO-->
{% block title %}About{% endblock  %}
{% block description %}{% endblock  %}
{% block keywords %}{% endblock  %}
<!--CSS-->
{% block extend_header %}{% endblock %}
<!--JS-->
 {% block extend_footer %}{% endblock  %}


{% block content %}
<!--==================== ABOUT ====================-->
        <section class="about section" id="about">
            <h2 class="section__title">About me</h2>
            <span class="section__subtitle">My introduction</span>
            <div class="about__container container grid">
                <img src="{{me.userprofile.about_image.url}}" alt="" class="about__img">
                <div class="about__data">
                    <p class="about__description">
                        {{me.userprofile.about_bio}}
                    </p>
                    <div class="about__info">
                        <div>
                            <span class="about__info-title">{{me.userprofile.experience}}+</span>
                            <span class="about__info-name">
                                Years <br> experience
                            </span>
                        </div>
                        <div>
                            <span class="about__info-title">{{me.userprofile.projects}}+</span>
                            <span class="about__info-name">
                                Completed <br> projects
                            </span>
                        </div>
                        <div>
                            <span class="about__info-title">{{me.userprofile.companies}}+</span>
                            <span class="about__info-name">
                                Companies <br> worked
                            </span>
                        </div>
                    </div>

                    <div class="about__buttons">
                        <a download="" href="{{me.userprofile.cv.url}}" class="button button--flex">
                            Tải về CV<i class="uil uil-file-download button__icon"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>
  <!--==================== PROJECT IN MIND ====================-->
        <section class="project section">
            <div class="project__bg">
                <div class="project__container container grid">
                    <div class="project__data">
                        <h2 class="project__title">You have new project</h2>
                        <p class="project__description">Liên lạc cho tôi và bạn sẽ nhận được thuê bao quý khách</p>
                        <a href="{% url 'main:contact' %}" class="button button--flex button--white">
                            Contact me
                            <i class="uil uil-message project__icon button__icon"></i>
                        </a>
                    </div>
                    <img src="{% static 'images/project.png' %}" alt="" class="project__img">
                </div>
            </div>

        </section>

    {% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--==================== UNICONS ====================-->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
    <script src="https://kit.fontawesome.com/0fa6b9267c.js" crossorigin="anonymous"></script>
   
    <!--==================== SWIPER CSS ====================-->
   

    <!--==================== CSS ====================-->
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extend_header%}{% endblock  %}

    <title>{% block title %}{% endblock  %}</title>
    <meta name="author" content="Quang Dong">
    <link rel="canonical" href="{{request.path}}" />
    <link rel="home" href="{% url 'main:home' %}" />
    <meta name="description" content="{% block description %}{% endblock  %}">
    <meta name="keywords" content="{% block keywords %}{% endblock  %}">
</head>

<body>
    {% include 'main/partials/nav.html' %}
    {% include 'main/partials/messages.html' %}

    <!--==================== MAIN ====================-->
    <main class="main">
        {% block content %}{% endblock  %}
    </main>
    {% include 'main/partials/footer.html' %}


    <!--==================== SWIPER JS ====================-->
   

    <!--==================== MAIN JS ====================-->
 
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
   
    {% block extend_footer %}{% endblock  %}
</body>

</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!--SEO-->
{% block title %}Portfolio Website{% endblock  %}
{% block description %}{% endblock  %}
{% block keywords %}{% endblock  %}
<!--CSS-->
{% block extend_header %}{% endblock %}
<!--JS-->
 {% block extend_footer %}{% endblock  %}


{% block content %}
<!--==================== HOME ====================-->
        <section class="home section" id="home">
            <div class="home__container container grid">
                <div class="home__content grid">
                    <div class="home__social">
                        <a href="https://www.facebook.com/" target="_blank" class="home__social-icon">
                            <i class="uil uil-facebook-f"></i>
                        </a>
                        <a href="https://www.instagram.com/" target="_blank" class="home__social-icon">
                            <i class="uil uil-instagram-alt"></i>
                        </a>
                        <a href="https://github.com/" target="_blank" class="home__social-icon">
                            <i class="uil uil-github"></i>
                        </a>
                    </div>
                    <div class="home__img">
                        <svg class="home__blob" viewBox="0 0 200 187" xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink">
                            <mask id="mask0" mask-type="alpha">
                                <path d="M190.312 36.4879C206.582 62.1187 201.309 102.826 182.328 134.186C163.346 165.547 
                                                        130.807 187.559 100.226 186.353C69.6454 185.297 41.0228 161.023 21.7403 129.362C2.45775 
                                                        97.8511 -7.48481 59.1033 6.67581 34.5279C20.9871 10.1032 59.7028 -0.149132 97.9666 
                                                        0.00163737C136.23 0.303176 174.193 10.857 190.312 36.4879Z" />
                            </mask>
                            <g mask="url(#mask0)">
                                <path
                                    d="M190.312 36.4879C206.582 62.1187 201.309 102.826 182.328 134.186C163.346 
                                                        165.547 130.807 187.559 100.226 186.353C69.6454 185.297 41.0228 161.023 21.7403 
                                                        129.362C2.45775 97.8511 -7.48481 59.1033 6.67581 34.5279C20.9871 10.1032 59.7028 
                                                        -0.149132 97.9666 0.00163737C136.23 0.303176 174.193 10.857 190.312 36.4879Z" />
                                <image class="home__blob-img" x='25' y='40' xlink:href="{{ me.userprofile.avatar.url }}" />
                            </g>
                        </svg>
                    </div>
                    <div class="home__data">
                        <h1 class="home__title">
                            Hi,{{me.userprofile.name|title}} nè
                        </h1>
                        <h3 class="home__subtitle">
                           {{me.userprofile.sub_title}}
                        </h3>
                        <p class="home__description">
                            {{me.userprofile.bio}}
                        </p>
                        <a href="{% url 'main:contact' %}" class="button button--flex">
                            Liên hệ tui <i class="uil uil-message button__icon"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    <!--==================== PROJECT IN MIND ====================-->
        <section class="project section">
            <div class="project__bg">
                <div class="project__container container grid">
                    <div class="project__data">
                        <h2 class="project__title">You have new project</h2>
                        <p class="project__description">Liên lạc cho tôi và bạn sẽ nhận được thuê bao quý khách</p>
                        <a href="{% url 'main:contact' %}" class="button button--flex button--white">
                            Contact me
                            <i class="uil uil-message project__icon button__icon"></i>
                        </a>
                    </div>
                    <img src="{% static 'images/project.png' %}" alt="" class="project__img">
                </div>
            </div>

        </section>
{% endblock  %}

main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!--SEO-->
{% block title %}Portfolios{% endblock  %}
{% block description %}{% endblock  %}
{% block keywords %}{% endblock  %}
<!--CSS-->
{% block extend_header %}{% endblock %}
<!--JS-->
{% block extend_footer %}{% endblock  %}


{% block content %}
 <!--==================== PORTFOLIO ====================-->
        <section class="portfolio section" id="portfolio">
            <h2 class="section__title">Portfolio</h2>
            <span class="section__subtitle">Most recently work</span>

            <div class="portfolio__container container swiper mySwiper">
                <div class="swiper-wrapper">
                     {% for obj in object_list  %}
                    <!--==================== PORTFOLIO 1====================-->
                    <div class="portfolio__content grid swiper-slide">
                        <img src="{{obj.image.url}}" alt="" class="portfolio__img">
                        <div class="portfolio__data">
                            <h3 class="portfolio__title">{{obj.name|title}}</h3>
                            <p class="portfolio__description">{{obj.description|safe}}</p>
                            <a href="{% url 'main:portfolio_detail' slug=obj.slug %}" class="button button--flex button--small portfolio__button">
                                Demo
                                <i class="uil uil-arrow-right button__icon"></i>
                            </a>
                        </div>
                    </div>
                     {% endfor %}
                </div>
                <div class="swiper-button-next">
                    <i class="uil uil-angle-right-b swiper-portfolio-icon"></i>
                </div>
                <div class="swiper-button-prev">
                    <i class="uil uil-angle-left-b swiper-portfolio-icon"></i>
                </div>

                <div class="swiper-pagination"></div>
            </div>
        </section>
    <!--==================== PROJECT IN MIND ====================-->
        <section class="project section">
            <div class="project__bg">
                <div class="project__container container grid">
                    <div class="project__data">
                        <h2 class="project__title">You have new project</h2>
                        <p class="project__description">Liên lạc cho tôi và bạn sẽ nhận được thuê bao quý khách</p>
                        <a href="{% url 'main:contact' %}" class="button button--flex button--white">
                            Contact me
                            <i class="uil uil-message project__icon button__icon"></i>
                        </a>
                    </div>
                    <img src="{% static 'images/project.png' %}" alt="" class="project__img">
                </div>
            </div>

        </section>
{% endblock %}

main/templates/main/portfolio_detail.html
{% extends 'main/base.html' %}
{% load static %}

<!--SEO-->
{% block title %}{{object.name|title}}{% endblock  %}
{% block description %}{% endblock  %}
{% block keywords %}{% endblock  %}
<!--CSS-->
{% block extend_header %}{% endblock %}
<!--JS-->
{% block extend_footer %}{% endblock  %}


{% block content %}
 

    <!--==================== Portfolio Detail ====================-->

<section class="detail section" >
    <div class="detail__container container">
        <h2>{{object.name|title}}</h2>
        <p>{{object.description}}</p>
        <div class="detail">
            <div class="video">
                <video id="video"><source src="{{object.demo.url}}" type="video/mp4" />
            </div>
        </div>
        
    </div>
</section>

{% endblock %}

main/templates/main/qualification.html
{% extends 'main/base.html' %}
{% load static %}

<!--SEO-->
{% block title %}Qualification{% endblock  %}
{% block description %}{% endblock  %}
{% block keywords %}{% endblock  %}
<!--CSS-->
{% block extend_header %}{% endblock %}
<!--JS-->
 {% block extend_footer %}{% endblock  %}


{% block content %}
 <!--==================== QUALIFICATION ====================-->
        <section class="qualification section">
            <h2 class="section__title">Qualification</h2>
            <span class="section__subtitle">My personal journey</span>
            <div class="qualification__container container">
                <div class="qualification__tabs">
                    <div class="qualification__button button--flex qualification__active" data-target='#education'>
                        <i class="uil uil-graduation-cap qualification__icon">
                            Education
                        </i>
                    </div>

                    <div class="qualification__button button--flex" data-target='#work'>
                        <i class="uil uil-briefcase-alt qualification__icon">
                            Work
                        </i>
                    </div>
                </div>
                <div class="qualification__sections">
                    <!--==================== QUALIFICATION CONTENT 1====================-->
                    <div class="qualification__content qualification__active" data-content id="education">
                        <!--==================== QUALIFICATION 1====================-->
                        {% for obj in object_list %}
                        {% if obj.sort_id == "edu" %}
                        {% if forloop.counter|divisibleby:2 %}
                        <div class="qualification__data">
                            
                            <div></div>
                            <div>
                                <span class="qualification__rounder"></span>
                                <span class="qualification__line"></span>
                            </div>
                            <div>
                                <h3 class="qualification__title">{{obj.title}}</h3>
                                <span class="qualification__subtitle">{{obj.sub_title}}</span>
                                <div class="qualification__calendar">
                                    <i class="uil uil-calendar-alt"></i>
                                    {{obj.year_from}}-{{obj.year_to}}
                                </div>
                            </div>
                            
                        </div>
                        {% else %}
                        <div class="qualification__data">
                            <div>
                                <h3 class="qualification__title">{{obj.title}}</h3>
                                <span class="qualification__subtitle">{{obj.sub_title}}</span>
                                <div class="qualification__calendar">
                                    <i class="uil uil-calendar-alt"></i>
                                    {{obj.year_from}}-{{obj.year_to}}
                                </div>
                            </div>
                            <div>
                                <span class="qualification__rounder"></span>
                                <span class="qualification__line"></span>
                            </div>
                        </div>
                        {% endif %}
                            {% endif %}
                            {% endfor %}
                    </div>

                    <!--==================== QUALIFICATION CONTENT 2====================-->
                   <div class="qualification__content " data-content id="work">
                        <!--==================== QUALIFICATION 1====================-->
                        {% for obj in object_list %}
                        {% if obj.sort_id == "wrk" %}
                        {% if forloop.counter|divisibleby:2 %}
                        <div class="qualification__data">
                            
                            <div></div>
                            <div>
                                <span class="qualification__rounder"></span>
                                <span class="qualification__line"></span>
                            </div>
                            <div>
                                <h3 class="qualification__title">{{obj.title}}</h3>
                                <span class="qualification__subtitle">{{obj.sub_title}}</span>
                                <div class="qualification__calendar">
                                    <i class="uil uil-calendar-alt"></i>
                                    {{obj.year_from}}-{{obj.year_to}}
                                </div>
                            </div>
                            
                        </div>
                        {% else %}
                        <div class="qualification__data">
                            <div>
                                <h3 class="qualification__title">{{obj.title}}</h3>
                                <span class="qualification__subtitle">{{obj.sub_title}}</span>
                                <div class="qualification__calendar">
                                    <i class="uil uil-calendar-alt"></i>
                                    {{obj.year_from}}-{{obj.year_to}}
                                </div>
                            </div>
                            <div>
                                <span class="qualification__rounder"></span>
                                <span class="qualification__line"></span>
                            </div>
                        </div>
                        {% endif %}
                            {% endif %}
                            {% endfor %}
                    </div>
                </div>
            </div>
        </section>
         <!--==================== PROJECT IN MIND ====================-->
        <section class="project section">
            <div class="project__bg">
                <div class="project__container container grid">
                    <div class="project__data">
                        <h2 class="project__title">You have new project</h2>
                        <p class="project__description">Liên lạc cho tôi và bạn sẽ nhận được thuê bao quý khách</p>
                        <a href="{% url 'main:contact' %}" class="button button--flex button--white">
                            Contact me
                            <i class="uil uil-message project__icon button__icon"></i>
                        </a>
                    </div>
                    <img src="{% static 'images/project.png' %}" alt="" class="project__img">
                </div>
            </div>

        </section>
{% endblock %}